# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu-16.04-desktop-amd64-java-dev"
  config.vm.synced_folder "~/virtual_box/", "/media/virtual_box", create: true, enabled: true, group: "vboxsf", mount_options: ['dmode=775', 'fmode=775']
  
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "ansible/playbook.yml"
  end
  
  config.vm.provider :virtualbox do |vb|
  #  Don't boot with headless mode
     vb.gui = true
     vb.memory = 10240
     vb.cpus = 2
  end
end
