- hosts: all
  sudo: true
  vars:
    username: tecris
  roles:
    - { role: ansible-screen }
    - { role: docker.ubuntu,
      docker_opts: "-H tcp://0.0.0.0:4243 -H unix:///var/run/docker.sock --registry-mirror=https://registry.mirror:5000"
    }
    - { role: ansible-java, java_oracle_version: 8u66 }
    - { role: ansible-maven }
  tasks:
    - name: Configure docker for given user
      action: shell sudo usermod -aG docker tecris
      action: shell git config --global user.email "eugen@cristea.org"
      action: shell git config --global user.name "Eugen Cristea"
    - name: Installs tree
      apt: pkg=cryptsetup state=installed update_cache=true
    - name: Installs cryptsetup package
      apt: pkg=tree state=installed update_cache=true
    - name: Installs git
      apt: pkg=git state=installed update_cache=true
    - name: screen configuration file
      copy: src=files/screenrc dest=/home/{{username}}/.screenrc owner={{username}} mode=0644
    - name: vim configuration file
      copy: src=files/vimrc dest=/home/{{username}}/.vimrc owner={{username}} mode=0644
    - name: ssh config
      file: path=/home/{{username}}/.ssh owner={{username}} group={{username}} state=directory mode=0700
      copy: src=files/ssh_config dest=/home/{{username}}/.ssh/config owner={{username}} mode=0644
    - name: ftp config
      copy: src=files/netrc dest=/home/{{username}}/.netrc owner={{username}} mode=0644
    - name: Configure hosts
      lineinfile:
        dest: /etc/hosts
        line: "{{ item.line }}"
      with_items:
        - { line: ''}
        - { line: '127.0.1.1       registry.mirror' }
        - { line: '172.17.0.1      blue.sky' }
