- hosts: all
  roles:
    - { role: docker.ubuntu,
      docker_opts: "-H tcp://0.0.0.0:4243 -H unix:///var/run/docker.sock --registry-mirror=https://registry.mirror:5000"
    }
    - { role: ansible-java, java_oracle_version: 8u66 }
    - { role: ansible-maven }
    - { role: ansible-screen }
  tasks:
    - name: Installs cryptsetup package
      apt: pkg=cryptsetup state=installed update_cache=true
