- hosts: all
  become: true
  become_method: sudo
  vars:
    username: tecris
  roles:
    - { role: williamyeh.oracle-java, java_version: 8, java_subversion: 72 }
    - { role: tecris.maven, maven_major: 3, maven_version: 3.3.9 }
    - { role: tersmitten.screen }
    - { role: angstwad.docker_ubuntu,
      docker_opts: "-H tcp://0.0.0.0:4243 -H unix:///var/run/docker.sock --registry-mirror=https://registry.mirror:5000"
    }
    - { role: geerlingguy.git }
  tasks:
    # task marked with tag to be executed only when run in docker (it is expected user tecris already exists when executed in development machine)
    - name: Add user
      user: name={{username}}
      tags:
        - only-on-docker
    - name: Installs vim package
      apt: pkg=vim state=installed update_cache=true
    - name: Avoid using sudo when using docker command
      command: usermod -aG docker {{username}}
    - name: Configure git email
      command: git config --global user.email "eugen@cristea.org"
    - name: Configure git user
      action: shell git config --global user.name "Eugen Cristea"
    - name: Configure git editor to vim
      command: git config --global core.editor "vim"
    - name: Installs tree
      apt: pkg=cryptsetup state=installed update_cache=true
    - name: Installs cryptsetup package
      apt: pkg=tree state=installed update_cache=true
    - name: screen configuration file
      copy: src=files/screenrc dest=/home/{{username}}/.screenrc owner={{username}} mode=0644
    - name: vim configuration file
      copy: src=files/vimrc dest=/home/{{username}}/.vimrc owner={{username}} mode=0644
    - file: path=/home/{{username}}/.m2 owner={{username}} group={{username}} state=directory mode=0775
    - name: maven settings.xml
      copy: src=files/settings.xml dest=/home/{{username}}/.m2/settings.xml owner={{username}} mode=0644
    - file: path=/home/{{username}}/.ssh owner={{username}} group={{username}} state=directory mode=0700
    - name: ssh config
      copy: src=files/ssh_config dest=/home/{{username}}/.ssh/config owner={{username}} mode=0644
    - name: ftp config
      copy: src=files/netrc dest=/home/{{username}}/.netrc owner={{username}} mode=0644
    # task marked with tag to be excluded from execution when running in docker ( cannot edit /etc/hosts with ansible )
    - name: Configure hosts
      lineinfile:
        dest: /etc/hosts
        line: "{{ item.line }}"
      with_items:
        - { line: ''}
        - { line: '127.0.1.1       registry.mirror' }
        - { line: '172.17.0.1      blue.sky' }
      tags:
        - no-docker
