- hosts: all
  vars:
    username: tecris
  roles:
    - { role: ansible-screen }
    - { role: docker.ubuntu,
      docker_opts: "-H tcp://0.0.0.0:4243 -H unix:///var/run/docker.sock --registry-mirror=https://registry.mirror:5000"
    }
    - { role: ansible-java, java_oracle_version: 8u66 }
    - { role: ansible-maven }
  tasks:
    - name: Installs tree
      apt: pkg=cryptsetup state=installed update_cache=true
    - name: Installs cryptsetup package
      apt: pkg=tree state=installed update_cache=true
    - name: Installs git
      apt: pkg=git state=installed update_cache=true
    - name: screen configuration file
      copy: src=files/screenrc dest=/home/{{username}}/.screenrc owner={{username}} mode=0644
    - name: vim configuration file
      copy: src=files/vimrc dest=/home/{{username}}/.vimrc owner={{username}} mode=0644
    - name: ssh config
      copy: src=files/ssh_config dest=/home/{{username}}/.ssh/config owner={{username}} mode=0644
    - name: ftp config
      copy: src=files/netrc dest=/home/{{username}}/.netrc owner={{username}} mode=0644
