- hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: Install gnome-key-ring
      apt:
        name: libgnome-keyring-dev
        state: present
    - name: compile the Gnome Keyring devel
      command: make --directory=/usr/share/doc/git/contrib/credential/gnome-keyring
    - name: Setup credentials
      command: git config --global credential.helper /usr/share/doc/git/contrib/credential/gnome-keyring/git-credential-gnome-keyring
    - name: Add php5.6 PPA
      command: add-apt-repository ppa:ondrej/php
    - command: apt-get update
    - command: apt-get -y install php5.6 php5.6-xml
